<?php

namespace ContainerFntY30G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompanyTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\CompanyType' shared autowired service.
     *
     * @return \App\Form\Type\CompanyType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/CompanyType.php';

        return $container->privates['App\\Form\\Type\\CompanyType'] = new \App\Form\Type\CompanyType();
    }
}
