<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8ZenZHC\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8ZenZHC/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container8ZenZHC.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container8ZenZHC\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \Container8ZenZHC\App_KernelTestDebugContainer([
    'container.build_hash' => '8ZenZHC',
    'container.build_id' => '7267bb3d',
    'container.build_time' => 1718103474,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container8ZenZHC');
