<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCbS8e6W\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCbS8e6W/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerCbS8e6W.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerCbS8e6W\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerCbS8e6W\App_KernelTestDebugContainer([
    'container.build_hash' => 'CbS8e6W',
    'container.build_id' => 'ee3db5af',
    'container.build_time' => 1717192712,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCbS8e6W');
