<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRg6frhi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRg6frhi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRg6frhi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRg6frhi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRg6frhi\App_KernelDevDebugContainer([
    'container.build_hash' => 'Rg6frhi',
    'container.build_id' => '660cea8c',
    'container.build_time' => 1717599768,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRg6frhi');
