<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNSEmx1i\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNSEmx1i/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNSEmx1i.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNSEmx1i\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNSEmx1i\App_KernelDevDebugContainer([
    'container.build_hash' => 'NSEmx1i',
    'container.build_id' => '4557a968',
    'container.build_time' => 1717879394,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNSEmx1i');
