<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_app_companies' => [[], ['_controller' => 'App\\Controller\\CompanyController::getCompanies'], [], [['text', '/api/companies']], [], [], []],
    'App\Controller\CompanyController::getCompanies' => [[], ['_controller' => 'App\\Controller\\CompanyController::getCompanies'], [], [['text', '/api/companies']], [], [], []],
];
